favicon: null
name: Stoke Row
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7547092109452933
  brandStrength: 0.8237815801985562
  lightness: 0.9039367840159684
  brandColors:
    - '#C5CDDA'
    - '#9DABB7'
    - '#15170E'
    - '#564626'
    - '#80642C'
  rhythmicContrast: 0.8797807744704187
typography_spectrum: 0.5765957
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
